name: Welcome to Cholla 
description: Cholla development blog 
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments
github: [Repository metadata]

paginate: 20
baseurl: /cholla
domain_name: 'http://evaneschneider.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://evaneschneider.github.io/cholla'
author:         'Evan Schneider'
authorTwitter:  'navelation'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
